export DATA_DIR=/home/sjtu/wrx/code/TinyZero-main/data/diagnosis-instruct-hint-icd10-0224-1200-shuffle-400-simple
# export BASE_MODEL=/data/sjtu/wrx/llamafactory/qwen2-7b-instruct-deepseek-pattern-diagnosis_knowledge_injection-orpo-0224-merge
export BASE_MODEL=/data/sjtu/wrx/llamafactory/psychgpt-coldstart-0303-merge
export ROLLOUT_TP_SIZE=2
export N_GPUS=4
export CUDA_VISIBLE_DEVICES=4,5,6,7
# ray stop --force && ray start --head --include-dashboard=True
export EXPERIMENT_NAME=diagnosis-instruct-qwen2-7b-coldstart-0303-2
export VLLM_ATTENTION_BACKEND=XFORMERS

# python -m verl.trainer.main_ppo \
#     data.train_files=$DATA_DIR/train.parquet \
#     data.val_files=$DATA_DIR/test.parquet \
#     data.train_batch_size=4 \
#     data.val_batch_size=4 \
#     data.max_prompt_length=2700 \
#     data.max_response_length=1024 \
#     actor_rollout_ref.model.path=$BASE_MODEL \
#     actor_rollout_ref.actor.optim.lr=1e-6 \
#     actor_rollout_ref.actor.ppo_mini_batch_size=2 \
#     actor_rollout_ref.actor.ppo_micro_batch_size=2 \
#     actor_rollout_ref.rollout.log_prob_micro_batch_size=4 \
#     actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
#     actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
#     actor_rollout_ref.ref.log_prob_micro_batch_size=4 \
#     actor_rollout_ref.model.enable_gradient_checkpointing=True \
#     critic.optim.lr=1e-5 \
#     critic.model.path=$BASE_MODEL \
#     critic.ppo_micro_batch_size=4 \
#     algorithm.kl_ctrl.kl_coef=0.001 \
#     trainer.logger=['wandb'] \
#     +trainer.val_before_train=False \
#     trainer.default_hdfs_dir=null \
#     trainer.n_gpus_per_node=$N_GPUS \
#     trainer.nnodes=1 \
#     trainer.save_freq=100 \
#     trainer.test_freq=100 \
#     trainer.project_name=TinyZero \
#     trainer.experiment_name=$EXPERIMENT_NAME \
#     trainer.total_epochs=15 2>&1 | tee verl_demo.log

python -m tinyzero.verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_batch_size=8 \
    data.val_batch_size=8 \
    data.max_prompt_length=512 \
    data.max_response_length=512 \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size=16 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=80 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=80 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='verl_grpo_diagnosis' \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=$N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq=45 \
    trainer.test_freq=45 \
    trainer.total_epochs=5 2>&1 | tee /home/sjtu/wrx/code/TinyZero-main/train_logs/coldstart-diagnosis.log